# Generated by Django 5.0.14 on 2026-09-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_analyticssnapshot_customreport_reportschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_teacher',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, default='A', max_length=50),
        ),
    ]
