# Generated by Django 5.0.14 on 2026-09-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_student_status_check_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='workflow_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
