# Generated by Django 5.0.14 on 2026-09-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_student_dob'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='application',
            name='chk_application_status_enum',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Pending_Clarification', 'Pending Clarification'), ('Under_Review', 'Under Review'), ('Offered', 'Offered'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Waitlisted', 'Waitlisted'), ('Active', 'Active')], default='Pending', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['Pending', 'Pending_Clarification', 'Under_Review', 'Offered', 'Accepted', 'Rejected', 'Waitlisted', 'Active'])), name='chk_application_status_enum'),
        ),
    ]
