# Generated by Django 5.0.14 on 2026-09-29 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from core.migrations.utils.rls import apply_rls_to_table, drop_rls_from_table


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0011_remove_application_chk_application_status_enum_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalRoleMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Principal', 'Principal'), ('Vice_Principal', 'Vice Principal'), ('Teacher', 'Teacher'), ('CareGiver', 'Caregiver'), ('Parent', 'Parent'), ('Vendor', 'Vendor'), ('Owner', 'Owner'), ('Board', 'Board'), ('Trustee', 'Trustee'), ('Staff', 'Staff')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_memberships', to='auth.group')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_memberships', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_portal_role_membership',
            },
        ),
        migrations.AddConstraint(
            model_name='portalrolemembership',
            constraint=models.UniqueConstraint(fields=('user', 'tenant'), name='uq_portal_role_membership_user_tenant'),
        ),
        migrations.RunSQL(
            sql=apply_rls_to_table('core_portal_role_membership'),
            reverse_sql=drop_rls_from_table('core_portal_role_membership'),
        ),
    ]
