# Generated by Django 5.0.14 on 2026-09-30 20:15

from django.db import migrations, models


def normalize_student_statuses(apps, schema_editor):
    Student = apps.get_model('core', 'Student')
    students = Student.objects.using(schema_editor.connection.alias)
    students.filter(status='Accepted').update(status='Active')
    students.exclude(status__in=['Active', 'Inactive', 'Waitlisted']).update(
        status='Inactive'
    )


def restore_legacy_student_statuses(apps, schema_editor):
    Student = apps.get_model('core', 'Student')
    Student.objects.using(schema_editor.connection.alias).filter(
        status='Inactive'
    ).update(status='Withdrawn')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_student_attendance_statuses'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='chk_student_status_enum',
        ),
        migrations.RunPython(
            normalize_student_statuses,
            restore_legacy_student_statuses,
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Waitlisted', 'Waitlisted')], default='Inactive', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['Active', 'Inactive', 'Waitlisted'])), name='chk_student_status_enum'),
        ),
    ]
