# Generated by Django 5.0.14 on 2026-10-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_payment_stripe_checkout_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
