# Generated by Django 5.0.14 on 2026-10-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_payment_checkout_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_currency',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
