# Generated by Django 5.2.11 on 2026-02-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skucore', '0002_studentonboardingrequest_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
        migrations.AddField(
            model_name='studentonboardingrequest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='onboarding_photos/'),
        ),
    ]
