# Generated by Django 5.2.11 on 2026-02-14 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skucore', '0004_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='onboarding_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='skucore.studentonboardingrequest'),
        ),
        migrations.AlterField(
            model_name='record',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='skucore.student'),
        ),
    ]
