# Generated by Django 5.2.11 on 2026-02-17 00:01

from django.db import migrations


def assign_to_default_school(apps, schema_editor):
    """Assign all existing records with school=None to default school"""
    School = apps.get_model('skucore', 'School')
    Grade = apps.get_model('skucore', 'Grade')
    Subject = apps.get_model('skucore', 'Subject')
    Route = apps.get_model('skucore', 'Route')
    Bus = apps.get_model('skucore', 'Bus')
    Parent = apps.get_model('skucore', 'Parent')
    Student = apps.get_model('skucore', 'Student')
    Attendance = apps.get_model('skucore', 'Attendance')
    StudentOnboardingRequest = apps.get_model('skucore', 'StudentOnboardingRequest')
    Record = apps.get_model('skucore', 'Record')
    UserRole = apps.get_model('skucore', 'UserRole')
    
    try:
        default_school = School.objects.get(code='DEFAULT')
        
        # Update all records with school=None
        Grade.objects.filter(school__isnull=True).update(school=default_school)
        Subject.objects.filter(school__isnull=True).update(school=default_school)
        Route.objects.filter(school__isnull=True).update(school=default_school)
        Bus.objects.filter(school__isnull=True).update(school=default_school)
        Parent.objects.filter(school__isnull=True).update(school=default_school)
        Student.objects.filter(school__isnull=True).update(school=default_school)
        Attendance.objects.filter(school__isnull=True).update(school=default_school)
        StudentOnboardingRequest.objects.filter(school__isnull=True).update(school=default_school)
        Record.objects.filter(school__isnull=True).update(school=default_school)
        UserRole.objects.filter(school__isnull=True).update(school=default_school)
        
        print(f"✓ Assigned all existing records to {default_school.name}")
    except School.DoesNotExist:
        print("⚠ Default school not found. Run setup_multi_tenancy.py to create it.")


class Migration(migrations.Migration):

    dependencies = [
        ('skucore', '0007_school_alter_bus_bus_number_alter_grade_grade_name_and_more'),
    ]

    operations = [
        migrations.RunPython(assign_to_default_school),
    ]
