import json
import logging
from datetime import date
from decimal import Decimal
from typing import Any, Dict, List, Optional
from uuid import UUID

from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.db import transaction

from core.business_objects.academic import (
    AcademicCalendarBO,
    AcademicRecordBO,
    ClassroomPlanBO,
    ExamPackageBO,
)
from core.business_objects.attendance_health import (
    AttendanceSheetBO,
    LeaveCaseBO,
)
from core.business_objects.sprint5 import (
    CommunicationBundleBO,
    ProcurementOrderBO,
    SchoolEventBO,
    StaffMemberBO,
    VendorAccountBO,
)
from core.models import (
    AcademicCalendar,
    Curriculum,
    Exam,
    FeeStructure,
    MarksRecord,
    Parent,
    PortalRoleMembership,
    Staff,
    StaffAttendance,
    Student,
    StudentAttendance,
    Tenant,
    Vendor,
    generate_student_number,
)
from core.schemas.academic import (
    AssignmentCreateSchema,
    CurriculumCreateSchema,
    ExamCreateSchema,
    LessonPlanCreateSchema,
    MarksEntrySchema,
)
from core.schemas.attendance_health import (
    AttendanceMarkSchema,
    LeaveRequestCreateSchema,
)
from core.schemas.billing import FeeStructureCreateSchema
from core.schemas.sprint5 import (
    EventCreateSchema,
    MessageCreateSchema,
    PurchaseOrderCreateSchema,
    StaffCreateSchema,
    VendorCreateSchema,
)

logger = logging.getLogger(__name__)


def _field(name: str, required: bool = False, example: str = "") -> Dict[str, Any]:
    return {"name": name, "required": required, "example": example}


DATASET_TEMPLATES = [
    {
        "key": "students",
        "group": "students",
        "label": "Students",
        "description": "Creates a Student and linked Parent only. Student numbers are generated by the current school; no admission request is created.",
        "fields": [
            _field("first_name", True, "Ava"),
            _field("last_name", True, "Collins"),
            _field("dob", example="2018-06-01"),
            _field("grade", True, "Pre-K"),
            _field("section", example="A"),
            _field("class_id"),
            _field("class_teacher"),
            _field("parent_name", True, "Sarah Collins"),
            _field("parent_relationship", example="Mother"),
            _field("parent_email", example="sarah@example.com"),
            _field("parent_phone", example="+15550100"),
        ],
    },
    {
        "key": "teachers", "group": "people", "label": "Teachers",
        "description": "Matches an existing login account and grants the Teacher role in this school.",
        "fields": [_field("first_name", True), _field("last_name", True), _field("email", True), _field("school_code", True)],
    },
    {
        "key": "parents", "group": "people", "label": "Parents",
        "description": "Parent contact fields linked to an imported student number.",
        "fields": [_field("student_number", True), _field("name", True), _field("relationship", True, "Parent"), _field("phone", True), _field("email"), _field("notification_prefs", example="{}"), _field("media_consent", example="false")],
    },
    {
        "key": "admins", "group": "people", "label": "Admins",
        "description": "Matches an existing login account and grants the Admin role in this school.",
        "fields": [_field("first_name", True), _field("last_name", True), _field("email", True), _field("school_code", True)],
    },
    {
        "key": "owners", "group": "people", "label": "Owners",
        "description": "Matches an existing login account and grants the Owner role in this school.",
        "fields": [_field("first_name", True), _field("last_name", True), _field("email", True), _field("school_code", True)],
    },
    {
        "key": "principals", "group": "people", "label": "Principals",
        "description": "Matches an existing login account and grants the Principal role in this school.",
        "fields": [_field("first_name", True), _field("last_name", True), _field("email", True), _field("school_code", True)],
    },
    {
        "key": "vendors", "group": "people", "label": "Vendors",
        "description": "VendorCreateSchema fields.",
        "fields": [_field("name", True), _field("contact_name"), _field("phone"), _field("email"), _field("payment_terms")],
    },
    {
        "key": "curriculums", "group": "operations", "label": "Curriculums",
        "description": "CurriculumCreateSchema fields; JSON arrays must be valid JSON.",
        "fields": [_field("grade", True), _field("version", example="1.0"), _field("subjects", example="[]"), _field("learning_outcomes", example="[]")],
    },
    {
        "key": "assessments", "group": "operations", "label": "Assessments",
        "description": "ExamCreateSchema fields. Leave calendar_id blank to use the current school calendar.",
        "fields": [_field("calendar_id"), _field("class_id", True), _field("name", True), _field("exam_type", example="Unit_Test"), _field("date", True, "2026-10-15"), _field("start_time", example="09:00"), _field("end_time", example="12:00"), _field("duration_mins", example="180"), _field("room"), _field("max_marks", example="100.00")],
    },
    {
        "key": "attendance", "group": "operations", "label": "Attendance Data",
        "description": "AttendanceMarkSchema fields. Student number may be used instead of UUID.",
        "fields": [_field("student_number"), _field("student_id"), _field("class_id"), _field("date", True, "2026-09-30"), _field("status", True, "Present"), _field("method", example="Manual"), _field("period", example="Full_Day")],
    },
    {
        "key": "events", "group": "operations", "label": "Events",
        "description": "EventCreateSchema fields.",
        "fields": [_field("title", True), _field("event_date", True, "2026-10-15"), _field("registration_deadline", True, "2026-10-10"), _field("location", True), _field("description"), _field("fee_amount", example="0.00"), _field("capacity", example="0"), _field("requires_permission_slip", example="true")],
    },
    {
        "key": "fee-structures", "group": "operations", "label": "Fee Structures",
        "description": "FeeStructureCreateSchema fields; components, discounts, and penalties are JSON.",
        "fields": [_field("grade", True), _field("term", True), _field("components", example='[{"description":"Tuition","amount":500}]'), _field("discount_rules", example="[]"), _field("penalty_rules", example="{}"), _field("version", example="1.0")],
    },
    {
        "key": "marks", "group": "operations", "label": "Marks",
        "description": "MarksEntrySchema fields. Use an existing exam and student UUID or student number.",
        "fields": [_field("exam_id", True), _field("student_number"), _field("student_id"), _field("subject", True), _field("marks", True), _field("max_marks", example="100")],
    },
    {
        "key": "lesson-plans", "group": "operations", "label": "Lesson Plans",
        "description": "LessonPlanCreateSchema fields. Use an existing curriculum UUID or grade/version in this school.",
        "fields": [_field("curriculum_id"), _field("curriculum_grade"), _field("curriculum_version"), _field("class_id", True), _field("week", True, "1"), _field("topic", True), _field("learning_outcomes", example="[]")],
    },
    {
        "key": "leave-plans", "group": "operations", "label": "Leave Plans",
        "description": "LeaveRequestCreateSchema fields. Student requesters may use a student number; staff may use a staff UUID or unique name.",
        "fields": [_field("requester_id"), _field("student_number"), _field("staff_id"), _field("staff_name"), _field("requester_type", True, "Staff"), _field("leave_type", True, "Annual"), _field("start_date", True, "2026-10-12"), _field("end_date", True, "2026-10-13"), _field("days", example="2"), _field("reason", True)],
    },
    {
        "key": "purchase-orders", "group": "operations", "label": "Purchase Orders",
        "description": "PurchaseOrderCreateSchema fields. Use a Vendor UUID from the import result.",
        "fields": [_field("vendor_id", True), _field("requisition_id"), _field("po_number", True), _field("amount", True), _field("expected_delivery_date", example="2026-10-20")],
    },
    {
        "key": "staff-details", "group": "operations", "label": "Staff Details",
        "description": "StaffCreateSchema fields.",
        "fields": [_field("name", True), _field("role", True), _field("dept", True), _field("employment_type", example="Full_Time"), _field("start_date", True, "2026-09-01"), _field("salary", example="0.00"), _field("certifications", example="[]"), _field("dbs_ref"), _field("dbs_expiry")],
    },
    {
        "key": "staff-attendances", "group": "operations", "label": "Staff Attendances",
        "description": "StaffAttendance fields. Use a Staff UUID from the Staff Details import result.",
        "fields": [_field("staff_id", True), _field("date", True, "2026-09-30"), _field("check_in"), _field("check_out"), _field("method", example="Manual"), _field("status", True, "Present"), _field("substitute_id"), _field("latitude"), _field("longitude"), _field("geofence_verified", example="false")],
    },
    {
        "key": "messages", "group": "operations", "label": "Messages",
        "description": "MessageCreateSchema fields; payload must be valid JSON.",
        "fields": [_field("channel", True, "Email"), _field("subject"), _field("body", True), _field("recipient_id"), _field("recipient_role"), _field("trigger_event"), _field("payload", example="{}")],
    },
]


class SchoolSetupImportError(Exception):
    def __init__(self, dataset: str, row_number: int, message: str):
        self.dataset = dataset
        self.row_number = row_number
        self.message = message
        super().__init__(f"{dataset} row {row_number}: {message}")


class SchoolSetupImportBO:
    @classmethod
    def import_dataset(
        cls,
        *,
        tenant: Tenant,
        dataset: str,
        records: List[Dict[str, Any]],
        actor_id: Optional[UUID],
        actor_role: str,
    ) -> Dict[str, Any]:
        if dataset not in {item['key'] for item in DATASET_TEMPLATES}:
            raise ValueError(f"Unsupported setup dataset: {dataset}")
        if not records:
            raise ValueError('At least one record is required.')
        if len(records) > 500:
            raise ValueError('A setup import may contain at most 500 records.')

        results = []
        with transaction.atomic():
            for row_number, row in enumerate(records, start=1):
                try:
                    results.append(
                        cls._import_record(tenant, dataset, row, actor_id, actor_role)
                    )
                except Exception as exc:
                    logger.exception("School setup import failed: %s row %s", dataset, row_number)
                    raise SchoolSetupImportError(dataset, row_number, str(exc)) from exc
        return {
            'dataset': dataset,
            'imported_count': len(results),
            'records': results,
        }

    @staticmethod
    def _date(value: Any) -> Optional[date]:
        if value in (None, ''):
            return None
        return value if isinstance(value, date) else date.fromisoformat(str(value).strip())

    @staticmethod
    def _json_value(value: Any, default: Any) -> Any:
        if value in (None, ''):
            return default
        return json.loads(value) if isinstance(value, str) else value

    @staticmethod
    def _student(tenant: Tenant, row: Dict[str, Any]) -> Student:
        student = None
        if row.get('student_id'):
            student = Student.objects.filter(
                student_id=row['student_id'], tenant=tenant, is_deleted=False
            ).first()
        if student is None and row.get('student_number'):
            student = Student.objects.filter(
                student_number=row['student_number'], tenant=tenant, is_deleted=False
            ).first()
        if student is None:
            raise ValueError('Student was not found in this school by student_id or student_number.')
        return student

    @staticmethod
    def _account_role(tenant: Tenant, row: Dict[str, Any], role: str) -> Dict[str, Any]:
        email = str(row.get('email') or '').strip().lower()
        if not email:
            raise ValueError('email is required to match an existing account.')
        school_code = str(row.get('school_code') or '').strip()
        if school_code and school_code.lower() != tenant.subdomain.lower():
            raise ValueError('school_code does not match the current school.')

        user_model = get_user_model()
        user = user_model.objects.filter(email__iexact=email).first()
        if user is None:
            raise ValueError(f'No existing account was found for {email}.')
        if not user.is_active:
            raise ValueError(f'The account for {email} is inactive.')

        group_name = 'Vice Principal' if role == 'Vice_Principal' else role
        group, _ = Group.objects.get_or_create(name=group_name)
        membership, _ = PortalRoleMembership.objects.update_or_create(
            user=user,
            tenant=tenant,
            defaults={'group': group, 'role': role, 'is_active': True},
        )
        return {
            'account_id': str(user.pk),
            'email': user.email,
            'role': role,
            'membership_id': str(membership.pk),
        }

    @classmethod
    def _import_record(
        cls,
        tenant: Tenant,
        dataset: str,
        row: Dict[str, Any],
        actor_id: Optional[UUID],
        actor_role: str,
    ) -> Dict[str, Any]:
        if dataset == 'students':
            missing = [
                field
                for field in ('first_name', 'last_name', 'grade', 'parent_name')
                if not str(row.get(field) or '').strip()
            ]
            if missing:
                raise ValueError(f"Missing required fields: {', '.join(missing)}")
            dob = cls._date(row.get('dob'))
            if dob and dob >= date.today():
                raise ValueError('Date of birth cannot be today or in the future.')
            class_id = row.get('class_id')
            student = Student.objects.create(
                tenant=tenant,
                student_number=generate_student_number(tenant),
                name=f"{str(row['first_name']).strip()} {str(row['last_name']).strip()}",
                dob=dob,
                grade=str(row['grade']).strip(),
                section=str(row.get('section') or 'A').strip(),
                class_id=UUID(str(class_id).strip()) if class_id else None,
                class_teacher=str(row.get('class_teacher') or '').strip(),
                status='Inactive',
                created_by=actor_id,
            )
            parent = Parent.objects.create(
                tenant=tenant,
                student=student,
                name=str(row['parent_name']).strip(),
                relationship=str(row.get('parent_relationship') or 'Parent').strip(),
                email=str(row.get('parent_email') or '').strip().lower(),
                phone=str(row.get('parent_phone') or '').strip(),
                created_by=actor_id,
            )
            return {
                'student_id': str(student.student_id),
                'student_number': student.student_number,
                'name': student.name,
                'status': student.status,
                'parent_id': str(parent.parent_id),
            }

        if dataset == 'parents':
            student = cls._student(tenant, row)
            email = str(row.get('email') or '').strip().lower()
            parent = None
            if email:
                parent = Parent.objects.filter(
                    tenant=tenant, student=student, email__iexact=email, is_deleted=False
                ).first()
            if parent is None:
                parent = Parent.objects.filter(
                    tenant=tenant,
                    student=student,
                    name__iexact=str(row.get('name') or '').strip(),
                    is_deleted=False,
                ).first()
            values = {
                'name': str(row.get('name') or '').strip(),
                'relationship': str(row.get('relationship') or 'Parent').strip(),
                'phone': str(row.get('phone') or '').strip(),
                'email': email,
                'notification_prefs': cls._json_value(row.get('notification_prefs'), {}),
                'media_consent': str(row.get('media_consent') or 'false').lower() in {'true', '1', 'yes'},
            }
            if not values['name']:
                raise ValueError('name is required.')
            if parent:
                for field, value in values.items():
                    setattr(parent, field, value)
                parent.save()
            else:
                parent = Parent.objects.create(
                    tenant=tenant, student=student, created_by=actor_id, **values
                )
            if email and get_user_model().objects.filter(email__iexact=email, is_active=True).exists():
                cls._account_role(tenant, {'email': email}, 'Parent')
            return {'parent_id': str(parent.parent_id), 'student_number': student.student_number, 'email': email}

        role_for_dataset = {
            'teachers': 'Teacher',
            'admins': 'Admin',
            'owners': 'Owner',
            'principals': 'Principal',
        }
        if dataset in role_for_dataset:
            return cls._account_role(tenant, row, role_for_dataset[dataset])

        if dataset == 'vendors':
            payload = VendorCreateSchema.model_validate(row)
            vendor = VendorAccountBO.create_vendor(tenant=tenant, data=payload.model_dump())
            return {'vendor_id': str(vendor.vendor_id), 'name': vendor.name, 'email': vendor.email}

        if dataset == 'staff-details':
            payload = StaffCreateSchema.model_validate({
                **row,
                'certifications': cls._json_value(row.get('certifications'), []),
            })
            staff = StaffMemberBO.create_staff(
                tenant=tenant, data=payload.model_dump(), actor_role=actor_role
            )
            return {'staff_id': str(staff.staff_id), 'name': staff.name, 'role': staff.role}

        if dataset == 'curriculums':
            payload = CurriculumCreateSchema.model_validate({
                **row,
                'subjects': cls._json_value(row.get('subjects'), []),
                'learning_outcomes': cls._json_value(row.get('learning_outcomes'), []),
            })
            curriculum = Curriculum.objects.create(tenant=tenant, **payload.model_dump())
            return {'curriculum_id': str(curriculum.curriculum_id), 'grade': curriculum.grade, 'version': curriculum.version}

        if dataset == 'assessments':
            payload = ExamCreateSchema.model_validate(row)
            calendar_query = AcademicCalendar.objects.filter(
                tenant=tenant, is_deleted=False
            )
            calendar = calendar_query.filter(calendar_id=payload.calendar_id).first() if payload.calendar_id else calendar_query.order_by('-academic_year').first()
            if calendar is None:
                raise ValueError('Create an academic calendar or provide a valid calendar_id first.')
            exam = ExamPackageBO.create_exam(
                tenant=tenant,
                calendar=calendar,
                class_id=payload.class_id,
                name=payload.name,
                exam_type=payload.exam_type,
                exam_date=payload.date,
                start_time=payload.start_time,
                end_time=payload.end_time,
                duration_mins=payload.duration_mins,
                room=payload.room or '',
                max_marks=payload.max_marks,
                actor_role=actor_role,
            )
            return {'exam_id': str(exam.exam_id), 'name': exam.name, 'date': exam.date.isoformat()}

        if dataset == 'attendance':
            payload_row = dict(row)
            if not payload_row.get('student_id') and payload_row.get('student_number'):
                payload_row['student_id'] = cls._student(tenant, payload_row).student_id
            student = cls._student(tenant, payload_row)
            if not payload_row.get('class_id'):
                payload_row['class_id'] = student.class_id
            if not payload_row.get('class_id'):
                raise ValueError('class_id is required when the student has no assigned class.')
            payload = AttendanceMarkSchema.model_validate(payload_row)
            record = AttendanceSheetBO.mark_attendance(
                tenant=tenant,
                student=student,
                class_id=payload.class_id,
                att_date=payload.date,
                status=payload.status,
                marked_by=actor_id or UUID(int=0),
                method=payload.method,
                period=payload.period,
                actor_role=actor_role,
            )
            return {'attendance_id': str(record.att_id), 'student_number': student.student_number, 'status': record.status}

        if dataset == 'marks':
            exam_id = row.get('exam_id')
            exam = Exam.objects.filter(exam_id=exam_id, tenant=tenant, is_deleted=False).first()
            if exam is None:
                raise ValueError('exam_id must reference an existing exam in this school.')
            student = cls._student(tenant, row)
            payload = MarksEntrySchema.model_validate({key: value for key, value in row.items() if key != 'exam_id'})
            mark = AcademicRecordBO.record_marks(
                tenant=tenant,
                student=student,
                exam=exam,
                teacher_id=actor_id or UUID(int=0),
                subject=payload.subject,
                marks=payload.marks,
                max_marks=payload.max_marks,
                actor_role=actor_role,
            )
            return {'marks_id': str(mark.marks_id), 'student_number': student.student_number, 'grade': mark.grade}

        if dataset == 'lesson-plans':
            payload_row = dict(row)
            curriculum_id = payload_row.get('curriculum_id')
            curriculum_query = Curriculum.objects.filter(tenant=tenant, is_deleted=False)
            if curriculum_id:
                curriculum = curriculum_query.filter(curriculum_id=curriculum_id).first()
            else:
                curriculum_grade = str(payload_row.get('curriculum_grade') or '').strip()
                curriculum_version = str(payload_row.get('curriculum_version') or '1.0').strip()
                if not curriculum_grade:
                    raise ValueError('Provide curriculum_id or curriculum_grade and curriculum_version.')
                matches = curriculum_query.filter(
                    grade__iexact=curriculum_grade,
                    version=curriculum_version,
                )
                if matches.count() > 1:
                    raise ValueError('curriculum_grade and curriculum_version must identify a unique curriculum.')
                curriculum = matches.first()
            curriculum = Curriculum.objects.filter(
                curriculum_id=curriculum.curriculum_id, tenant=tenant, is_deleted=False
            ).first() if curriculum else None
            if curriculum is None:
                raise ValueError('Curriculum must reference an existing curriculum in this school.')
            payload_row['curriculum_id'] = str(curriculum.curriculum_id)
            payload_row.pop('curriculum_grade', None)
            payload_row.pop('curriculum_version', None)
            payload_row['learning_outcomes'] = cls._json_value(payload_row.get('learning_outcomes'), [])
            payload = LessonPlanCreateSchema.model_validate(payload_row)
            plan = ClassroomPlanBO.create_lesson_plan(
                tenant=tenant,
                teacher_id=actor_id or UUID(int=0),
                curriculum=curriculum,
                class_id=payload.class_id,
                week=payload.week,
                topic=payload.topic,
                learning_outcomes=payload.learning_outcomes,
                actor_role=actor_role,
            )
            return {'plan_id': str(plan.plan_id), 'topic': plan.topic, 'week': plan.week}

        if dataset == 'leave-plans':
            payload_row = dict(row)
            requester_type = str(payload_row.get('requester_type') or '').strip()
            requester_id = payload_row.get('requester_id')
            if requester_type == 'Student':
                student_row = dict(payload_row)
                if requester_id:
                    student_row['student_id'] = requester_id
                requester_id = cls._student(tenant, student_row).student_id
            elif requester_type == 'Staff':
                staff_query = Staff.objects.filter(tenant=tenant, is_deleted=False)
                if requester_id or payload_row.get('staff_id'):
                    staff_id = requester_id or payload_row.get('staff_id')
                    staff = staff_query.filter(staff_id=staff_id).first()
                else:
                    staff_name = str(payload_row.get('staff_name') or '').strip()
                    matches = staff_query.filter(name__iexact=staff_name) if staff_name else staff_query.none()
                    if matches.count() > 1:
                        raise ValueError('staff_name must identify a unique staff member in this school.')
                    staff = matches.first()
                if staff is None:
                    raise ValueError('Staff requester was not found in this school.')
                requester_id = staff.staff_id
            else:
                raise ValueError('requester_type must be Student or Staff.')
            payload_row['requester_id'] = str(requester_id)
            for field in ('student_number', 'staff_id', 'staff_name'):
                payload_row.pop(field, None)
            payload = LeaveRequestCreateSchema.model_validate(payload_row)
            calendar = AcademicCalendar.objects.filter(tenant=tenant, is_deleted=False).order_by('-academic_year').first()
            calendar_bo = AcademicCalendarBO(calendar=calendar, actor_role=actor_role) if calendar else None
            leave = LeaveCaseBO.create_leave_request(
                tenant=tenant,
                requester_id=payload.requester_id,
                requester_type=payload.requester_type,
                leave_type=payload.leave_type,
                start_date=payload.start_date,
                end_date=payload.end_date,
                days=payload.days,
                reason=payload.reason,
                calendar_bo=calendar_bo,
                actor_role=actor_role,
            )
            return {'leave_id': str(leave.leave_id), 'requester_id': str(leave.requester_id), 'status': leave.status}

        if dataset == 'fee-structures':
            payload = FeeStructureCreateSchema.model_validate({
                **row,
                'components': cls._json_value(row.get('components'), []),
                'discount_rules': cls._json_value(row.get('discount_rules'), []),
                'penalty_rules': cls._json_value(row.get('penalty_rules'), {}),
            })
            fee = FeeStructure.objects.create(tenant=tenant, **payload.model_dump())
            return {'fee_struct_id': str(fee.fee_struct_id), 'grade': fee.grade, 'term': fee.term}

        if dataset == 'purchase-orders':
            payload = PurchaseOrderCreateSchema.model_validate(row)
            order = ProcurementOrderBO.create_purchase_order(tenant, payload.model_dump())
            return {'po_id': str(order.po_id), 'po_number': order.po_number, 'amount': float(order.amount)}

        if dataset == 'staff-attendances':
            staff = Staff.objects.filter(staff_id=row.get('staff_id'), tenant=tenant, is_deleted=False).first()
            if staff is None:
                raise ValueError('staff_id must reference a Staff Details record in this school.')
            att_date = cls._date(row.get('date'))
            if att_date is None:
                raise ValueError('date is required in YYYY-MM-DD format.')
            status = str(row.get('status') or 'Present')
            if status not in {'Present', 'Absent', 'Late', 'Half_Day', 'On_Leave'}:
                raise ValueError('status must be Present, Absent, Late, Half_Day, or On_Leave.')
            attendance, _ = StaffAttendance.objects.update_or_create(
                tenant=tenant,
                staff_id=staff.staff_id,
                date=att_date,
                defaults={
                    'check_in': row.get('check_in') or '',
                    'check_out': row.get('check_out') or '',
                    'method': row.get('method') or 'Manual',
                    'status': status,
                    'geofence_verified': str(row.get('geofence_verified') or 'false').lower() in {'true', '1', 'yes'},
                },
            )
            return {'staff_att_id': str(attendance.staff_att_id), 'staff_id': str(staff.staff_id), 'date': att_date.isoformat(), 'status': attendance.status}

        if dataset == 'messages':
            payload_row = dict(row)
            payload_row['payload'] = cls._json_value(row.get('payload'), {})
            payload = MessageCreateSchema.model_validate(payload_row)
            message = CommunicationBundleBO.create_message(tenant, payload.model_dump())
            return {'message_id': str(message.message_id), 'channel': message.channel, 'delivery_status': message.delivery_status}

        if dataset == 'events':
            payload = EventCreateSchema.model_validate(row)
            event = SchoolEventBO.create_event(tenant, payload.model_dump())
            return {'event_id': str(event.event_id), 'title': event.title, 'event_date': event.event_date.isoformat()}

        raise ValueError(f"Unsupported setup dataset: {dataset}")